"""MailFlow core: provider-independent domain, plugin pipeline, service facade."""

from mailflow.domain import (
    AccountSnapshot,
    ActionItem,
    ActionOrigin,
    Attachment,
    CommandResponse,
    ComponentKind,
    ComponentSnapshot,
    LLMSnapshot,
    MailAddress,
    MailAnalysis,
    MailMessage,
    MailRecord,
    PendingOperation,
    PluginSnapshot,
    ProcessorBindingSnapshot,
    ProcessorNote,
    ReplyDraft,
    ReplyState,
    RuntimeSnapshot,
    SeminarCandidate,
    SeminarDiscoveryResult,
    SeminarStatus,
    SmartActionResult,
    SmartSearchResult,
    StyleSpan,
    TrashRecord,
    Urgency,
    action_time_window,
    actions_duplicate,
    dedupe_actions,
    parse_urgency,
    to_utc,
    utcnow,
)

__version__ = "0.1.0"

__all__ = [
    "AccountSnapshot",
    "ActionItem",
    "ActionOrigin",
    "Attachment",
    "CommandResponse",
    "ComponentKind",
    "ComponentSnapshot",
    "LLMSnapshot",
    "MailAddress",
    "MailAnalysis",
    "MailMessage",
    "MailRecord",
    "PendingOperation",
    "PluginSnapshot",
    "ProcessorBindingSnapshot",
    "ProcessorNote",
    "ReplyDraft",
    "ReplyState",
    "RuntimeSnapshot",
    "SeminarCandidate",
    "SeminarDiscoveryResult",
    "SeminarStatus",
    "SmartActionResult",
    "SmartSearchResult",
    "StyleSpan",
    "TrashRecord",
    "Urgency",
    "__version__",
    "action_time_window",
    "actions_duplicate",
    "dedupe_actions",
    "parse_urgency",
    "to_utc",
    "utcnow",
]
